-- create tables
create table categories (
    id                             number not null constraint categories_id_pk primary key,
    name                           varchar2(50)
)
;


create table members (
    id                             number not null constraint members_id_pk primary key,
    username                       varchar2(50),
    firstname                      varchar2(30),
    lastname                       varchar2(30),
    mobilephone                    varchar2(20),
    emailaddress                   varchar2(100)
)
;

create table offers (
    id                             number not null constraint offers_id_pk primary key,
    categories_id                  number
                                   ,
    name                           varchar2(255),
    description                    varchar2(4000),
    members_id                     number
                                   ,
    image                          blob,
    status                         varchar2(40),
    thread                         varchar2(4000),
    handover_or_share              varchar2(1) constraint offers_handover_or_share_cc
                                   check (handover_or_share in ('H','S')),
    changetimestamp                      timestamp default systimestamp,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;

create table reactions (
    id                             number not null constraint reactions_id_pk primary key,
    offer_id                       number
                                   constraint reactions_offer_id_fk
                                   references offers on delete cascade,
    the_user                       varchar2(50),
    the_comment                    varchar2(4000),
    timestamp                      timestamp
)
;


-- triggers
create or replace trigger categories_biu
    before insert or update 
    on categories
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
end categories_biu;
/

create or replace trigger members_biu
    before insert or update 
    on members
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
end members_biu;
/

create or replace trigger offers_biu
    before insert or update 
    on offers
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
        begin
          select id into :new.members_id from members   where lower(username) = lower(sys_context('APEX$SESSION','APP_USER')) ;
        exception
          when no_data_found then null;
        end;
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end offers_biu;
/

create or replace trigger reactions_biu
    before insert or update 
    on reactions
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
end reactions_biu;
/


-- indexes
create index offers_i1 on offers (categories_id);
create index offers_i2 on offers (members_id);
create index reactions_i1 on reactions (offer_id);
-- load data
 
-- Generated by Quick SQL Sunday January 27, 2019  21:22:57
 
/*
categories
   name vc50

offers /auditcols
   name
   description
   members id  /fk members id
   image blob
   status vc40    
   categories id  
   handover_or_share vc1 /check h,s
   timestamp timestamp
   reactions
      user vc50
      comment vc
      timestamp timestamp

members
   username vc50 
   firstName vc30
   lastName vc30
   mobilePhone vc20
   emailAddress vc100

# settings = { PK: "TRIG", language: "EN", APEX: true }
*/


